# Generated by Django 4.1.5 on 2023-01-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-project_priority',)},
        ),
        migrations.AddField(
            model_name='project',
            name='project_priority',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
